### ISSUE TITLE
Unstable on aarch64

### ISSUE THREAD

**Issue by agners** [marcelstoer/open-data-smn#10]
I am running the open-data-smn container on a aarch64 platform. It seems that the container crashes from time to time hard due to a Java Runtime Error:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (assembler_aarch64.hpp:1156), pid=1, tid=0x0000ffff9e7d9aa0
#  guarantee(Rs != Rn && Rs != Rt) failed: unpredictable instruction
#
# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-aarch64 compressed oops)
# Derivative: IcedTea 3.12.0
# Distribution: Custom build (Sat May  4 17:44:26 UTC 2019)
# Core dump written. Default location: //core or core.1
#
# Can not save log file, dump to screen..
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (assembler_aarch64.hpp:1156), pid=1, tid=0x0000ffff9e7d9aa0
#  guarantee(Rs != Rn && Rs != Rt) failed: unpredictable instruction
#
# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-aarch64 compressed oops)
# Derivative: IcedTea 3.12.0
# Distribution: Custom build (Sat May  4 17:44:26 UTC 2019)
# Core dump written. Default location: //core or core.1
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   https://icedtea.classpath.org/bugzilla
...
```

Reading on the internet it seems that Java 11 or maybe already the latest alpine Java 8 packages don't show that problem: https://github.com/openhab/openhab-docker/issues/233

**Comment by marcelstoer** [comment]
I just pushed a newly built image to Docker Hub: https://hub.docker.com/r/marcelstoer/open-data-smn/tags?page=1&ordering=last_updated

BUT it was only after that I realized `openjdk:8-jre-alpine` is actually two years old: https://hub.docker.com/layers/openjdk/library/openjdk/8-jre-alpine/images/sha256-f7a292bbb70c4ce57f7704cc03eb09e299de9da19013b084f138154421918cb4?context=explore Hence, Java is still at 1.8.0_212.

Will have to try with `adoptopenjdk/openjdk8:alpine-jre` which'll give us OpenJDK 1.8.0_292.

**Comment by marcelstoer** [comment]
Ok, settled for `adoptopenjdk:8-jre-hotspot`.

**Comment by agners** [comment]
@marcelstoer thx for looking into this so quickly!

It seems that the location of the `java` executable moved. I get this when trying to run a container with the new image:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/usr/bin/java": stat /usr/bin/java: no such file or directory: unknown.
```

By passing the command manually I was able to start, so the image looks good otherwise:
```
docker run -d -p 4712:4712 --restart=always marcelstoer/open-data-smn /opt/java/openjdk/bin/java -jar /open-data-smn.jar server /open-data-smn.yml
```

**Comment by marcelstoer** [comment]
Weird...I tested the image locally as well and all was good. Will have to take another look I guess.

**Comment by marcelstoer** [comment]
I don't know _what_ I had been testing earlier - must have been the old image I guess. Either way, thanks for the analysis. The fix is on `master` and on Docker Hub.
