### ISSUE TITLE
Changes in data structure?

### ISSUE THREAD

**Issue by ChrisVolz** [marcelstoer/open-data-smn#6]
this nice api seems to be broken since a few days. It may be a consequence of the new open-data forum "https://opendata.swiss/de/", which went online at 2. februar 2016.

It would be great if this work could be conitnued and the api could be adapted to recent changes?

Best regards,
Christian

**Comment by marcelstoer** [comment]
Learned about the launch of the new portal today by coincidence (OKFN CH mailing list). I'm on vacation and with lousy Internet connection but I had planned to check on the impact of this for my service anyway tonight. Pretty bad "they" decommissioned existing URL just like that without any grace period or automatic redirects.
Anyway, a temporary fix is in place, the API is up and running again but a proper release will have to wait for a bit.

On a different note, what are you using the API for anyway?

**Comment by ChrisVolz** [comment]
that sounds great, thanks a lot!

well, currently I am only do some tests for presenting the swissmetnet-data on a web-map. The plan is to launch a site in future providing detailed information with rain radar, rain gauges and self-made computations (like rainfall-runoff).

rg, Christian
